name: 'Cancel Workflows'
description: 'Cancels workflows based on inputs'
inputs:
  token:
    description: 'Github token to use to authenticate'
    required: true
  branch: 
    description: 'The target branch of the workflows to cancel'
    required: true
  event: 
    description: 'The actions event that triggered the target workflows.'
    required: true
  run_number: 
    description: 'The run number of the current workflow run'
    required: true
  status:
    description: "Target workflow statuses seperated by a space."
    required: true
  waitfor:
    description: "Status to wait for before starting."
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
      - shell: bash
        run: |
          if [ ${{ inputs.waitfor }} != "" ];
          then
          echo "Waiting for workflows to no longer be in status ${{ inputs.waitfor }}..."
          for waitfor in ${{ inputs.waitfor }}; do
            while [ "$(curl -G \
            --data-urlencode 'branch=${{inputs.branch}}' \
            --data-urlencode 'event=${{inputs.event}}' \
            --data-urlencode "status=$status" \
            --data-urlencode 'per_page=100' \
            --header 'Authorization: token ${{inputs.token}}' \
            --header 'accept: application/vnd.github.v3+json' \
            --silent \
            https://api.github.com/repos/${{github.repository}}/actions/runs \
            | jq --raw-output '.total_count')" != "0" ]; do
              echo -n '.'
              sleep 1
            done
          done
          fi

      - shell: bash 
        run: |
          for status in ${{ inputs.status }}; do
            curl -G \
            --data-urlencode 'branch=${{inputs.branch}}' \
            --data-urlencode 'event=${{inputs.event}}' \
            --data-urlencode "status=$status" \
            --data-urlencode 'per_page=100' \
            --header 'Authorization: token ${{inputs.token}}' \
            --header 'accept: application/vnd.github.v3+json' \
            --silent \
            https://api.github.com/repos/${{github.repository}}/actions/runs \
            | jq --raw-output '.workflow_runs[] | select(.run_number!=${{inputs.run_number}}) | .url' \
            | for i in $(cat) ; do
              echo "Canceling workflow run id $i..."
              curl -X POST \
              --header 'Authorization: token ${{inputs.token}}' \
              --header 'accept: application/vnd.github.v3+json' \
              --silent \
              $i/cancel
            done
          done