name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  cancel-workflows:
    name: Cancel Workflow Runs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cancel Previou Workflow Runs
        uses: ./.github/actions/cancel-workflows-action
        with:
          token: ${{ github.token }}
          event: "push"
          branch: main
          #${{ github.head_ref }}
          run_number: ${{ github.run_number }}
          status: "queued waiting"
          waiton: "in_progress"

  # deploy-dev:
  #   environment: dev
  #   name: Dev
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v2
  #       with: { fetch-depth: 0 }
    
  #     - name: Echo
  #       run: echo "Dev Deploy"

  # deploy-staging:
  #   environment: staging
  #   name: Staging
  #   runs-on: ubuntu-latest
  #   needs: [deploy-dev]
    
  #   steps:
  #     - uses: actions/checkout@v2
  #       with: { fetch-depth: 0 }
    
  #     - name: Echo
  #       run: echo "Staging Deploy"

  # deploy-prod:
  #   environment: prod
  #   name: Prod
  #   runs-on: ubuntu-latest
  #   needs: [deploy-staging]
    
  #   steps:
  #     - uses: actions/checkout@v2
  #       with: { fetch-depth: 0 }
    
  #     - name: Echo
  #       run: echo "Prod Deploy"