name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy-dev:
    environment: dev
    name: Dev
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
    
      - name: Echo
        run: echo "Dev Deploy"

  deploy-staging:
    environment: staging
    name: Staging
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
    
      - name: Echo
        run: echo "Staging Deploy"

  deploy-prod:
    environment: prod
    name: Prod
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
    
      - name: Echo
        run: echo "Prod Deploy"