name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Dev
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
    
      - name: Echo
        run: echo "Dev Deploy"

  deploy-staging:
    name: Dev
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
    
      - name: Echo
        run: echo "Dev Deploy"

  deploy-prod:
    name: Dev
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
    
      - name: Echo
        run: echo "Dev Deploy"